// <auto-generated />
using System;
using BillingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillingSystem.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260123122159_AddPharmacyModule")]
    partial class AddPharmacyModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Healthcare")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillingSystem.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdmitDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FeePerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(2000m);

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AdmissionId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("AdmitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConsultationFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(500m);

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OptionalServicesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("SeniorDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId");

                    b.HasIndex("BillDate")
                        .HasDatabaseName("IX_Bill_BillDate");

                    b.HasIndex("PatientId");

                    b.ToTable("Bills", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.BillItem", b =>
                {
                    b.Property<int>("BillItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.HasKey("BillItemId");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctor", "Healthcare");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aditya",
                            IsAvailable = true,
                            LastName = "Verma",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sriya",
                            IsAvailable = true,
                            LastName = "Reddy",
                            Specialization = "Diagnostics"
                        },
                        new
                        {
                            DoctorId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vikram",
                            IsAvailable = true,
                            LastName = "Singh",
                            Specialization = "Radiology"
                        });
                });

            modelBuilder.Entity("BillingSystem.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceId"));

                    b.Property<double>("CoveragePercent")
                        .HasColumnType("float");

                    b.Property<int>("CoverageType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceId");

                    b.HasIndex("PatientId");

                    b.ToTable("Insurances", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.LabOrder", b =>
                {
                    b.Property<int>("LabOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabOrderId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Results")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LabOrderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("LabOrder", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageStrength")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines", "Healthcare");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            Category = "Analgesic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(1986),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Paracetamol",
                            PricePerUnit = 2m,
                            Stock = 1000
                        },
                        new
                        {
                            MedicineId = 2,
                            Category = "Antibiotic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(1994),
                            DosageStrength = "250mg",
                            ExpiryDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Amoxicillin",
                            PricePerUnit = 15m,
                            Stock = 500
                        },
                        new
                        {
                            MedicineId = 3,
                            Category = "Antihistamine",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(1997),
                            DosageStrength = "10mg",
                            ExpiryDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Cetirizine",
                            PricePerUnit = 5m,
                            Stock = 800
                        },
                        new
                        {
                            MedicineId = 4,
                            Category = "Antidiabetic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2000),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Metformin",
                            PricePerUnit = 8m,
                            Stock = 1200
                        },
                        new
                        {
                            MedicineId = 5,
                            Category = "Statin",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2003),
                            DosageStrength = "20mg",
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Atorvastatin",
                            PricePerUnit = 25m,
                            Stock = 300
                        },
                        new
                        {
                            MedicineId = 6,
                            Category = "Proton Pump Inhibitor",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2006),
                            DosageStrength = "20mg",
                            ExpiryDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Omeprazole",
                            PricePerUnit = 12m,
                            Stock = 500
                        },
                        new
                        {
                            MedicineId = 7,
                            Category = "Bloop Pressure",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2008),
                            DosageStrength = "5mg",
                            ExpiryDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Amlodipine",
                            PricePerUnit = 10m,
                            Stock = 600
                        },
                        new
                        {
                            MedicineId = 8,
                            Category = "Analgesic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2010),
                            DosageStrength = "400mg",
                            ExpiryDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ibuprofen",
                            PricePerUnit = 3m,
                            Stock = 900
                        },
                        new
                        {
                            MedicineId = 9,
                            Category = "Antibiotic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2012),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Azithromycin",
                            PricePerUnit = 45m,
                            Stock = 200
                        },
                        new
                        {
                            MedicineId = 10,
                            Category = "Beta Blocker",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2015),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Metoprolol",
                            PricePerUnit = 18m,
                            Stock = 400
                        },
                        new
                        {
                            MedicineId = 11,
                            Category = "Antihypertensive",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2017),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Losartan",
                            PricePerUnit = 22m,
                            Stock = 350
                        },
                        new
                        {
                            MedicineId = 12,
                            Category = "Anticonvulsant",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2019),
                            DosageStrength = "300mg",
                            ExpiryDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Gabapentin",
                            PricePerUnit = 35m,
                            Stock = 250
                        },
                        new
                        {
                            MedicineId = 13,
                            Category = "Antidepressant",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2022),
                            DosageStrength = "50mg",
                            ExpiryDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sertraline",
                            PricePerUnit = 40m,
                            Stock = 150
                        },
                        new
                        {
                            MedicineId = 14,
                            Category = "Proton Pump Inhibitor",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2026),
                            DosageStrength = "40mg",
                            ExpiryDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Pantoprazole",
                            PricePerUnit = 14m,
                            Stock = 500
                        },
                        new
                        {
                            MedicineId = 15,
                            Category = "Antiplatelet",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2029),
                            DosageStrength = "75mg",
                            ExpiryDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Aspirin",
                            PricePerUnit = 1m,
                            Stock = 2000
                        },
                        new
                        {
                            MedicineId = 16,
                            Category = "Corticosteroid",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2032),
                            DosageStrength = "5mg",
                            ExpiryDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Prednisone",
                            PricePerUnit = 20m,
                            Stock = 300
                        },
                        new
                        {
                            MedicineId = 17,
                            Category = "Bronchodilator",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2034),
                            DosageStrength = "100mcg",
                            ExpiryDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Salbutamol",
                            PricePerUnit = 150m,
                            Stock = 100
                        },
                        new
                        {
                            MedicineId = 18,
                            Category = "Diuretic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2036),
                            DosageStrength = "40mg",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Furosemide",
                            PricePerUnit = 6m,
                            Stock = 500
                        },
                        new
                        {
                            MedicineId = 19,
                            Category = "Insulin",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2038),
                            DosageStrength = "100U/ml",
                            ExpiryDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Insulin Glargine",
                            PricePerUnit = 800m,
                            Stock = 50
                        },
                        new
                        {
                            MedicineId = 20,
                            Category = "Antibiotic",
                            CreatedDate = new DateTime(2026, 1, 23, 17, 51, 58, 701, DateTimeKind.Local).AddTicks(2040),
                            DosageStrength = "500mg",
                            ExpiryDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ciprofloxacin",
                            PricePerUnit = 30m,
                            Stock = 400
                        });
                });

            modelBuilder.Entity("BillingSystem.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PatientId");

                    b.HasIndex("MobileNumber")
                        .HasDatabaseName("IX_Patient_MobileNumber");

                    b.ToTable("Patients", "Healthcare");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = 1,
                            IsActive = true,
                            LastName = "Doe",
                            MobileNumber = "9876543210"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = 2,
                            IsActive = true,
                            LastName = "Smith",
                            MobileNumber = "8765432109"
                        });
                });

            modelBuilder.Entity("BillingSystem.Models.PatientService", b =>
                {
                    b.Property<int>("PatientServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientServiceId"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("PatientServiceId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PatientServices", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.HasIndex("TransactionRef")
                        .HasDatabaseName("IX_Payment_TransactionRef");

                    b.ToTable("Payments", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescribedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuggestedQuantity")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Prescriptions", "Healthcare");
                });

            modelBuilder.Entity("BillingSystem.Models.ServiceMaster", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("IX_Service_Name");

                    b.ToTable("ServicesMaster", "Healthcare");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Cost = 600m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB001",
                            ServiceName = "Lab Test"
                        },
                        new
                        {
                            ServiceId = 2,
                            Cost = 300m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Radiology",
                            IsActive = true,
                            ServiceCode = "RAD001",
                            ServiceName = "X-Ray"
                        },
                        new
                        {
                            ServiceId = 3,
                            Cost = 1500m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Cardiology",
                            IsActive = true,
                            ServiceCode = "CRD001",
                            ServiceName = "ECG"
                        },
                        new
                        {
                            ServiceId = 4,
                            Cost = 2500m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Radiology",
                            IsActive = true,
                            ServiceCode = "RAD002",
                            ServiceName = "MRI"
                        },
                        new
                        {
                            ServiceId = 5,
                            Cost = 1200m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Radiology",
                            IsActive = true,
                            ServiceCode = "RAD003",
                            ServiceName = "Ultrasound"
                        },
                        new
                        {
                            ServiceId = 6,
                            Cost = 400m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB002",
                            ServiceName = "Blood Work"
                        },
                        new
                        {
                            ServiceId = 7,
                            Cost = 800m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB007",
                            ServiceName = "Lipid Profile"
                        },
                        new
                        {
                            ServiceId = 8,
                            Cost = 950m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB008",
                            ServiceName = "Kidney Function Test"
                        },
                        new
                        {
                            ServiceId = 9,
                            Cost = 1100m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB009",
                            ServiceName = "Thyroid Profile"
                        },
                        new
                        {
                            ServiceId = 10,
                            Cost = 100m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB010",
                            ServiceName = "Blood Sugar"
                        },
                        new
                        {
                            ServiceId = 11,
                            Cost = 1200m,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pathology",
                            IsActive = true,
                            ServiceCode = "LAB011",
                            ServiceName = "Liver Function Test"
                        });
                });

            modelBuilder.Entity("BillingSystem.Models.Admission", b =>
                {
                    b.HasOne("BillingSystem.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BillingSystem.Models.Appointment", b =>
                {
                    b.HasOne("BillingSystem.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BillingSystem.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BillingSystem.Models.Bill", b =>
                {
                    b.HasOne("BillingSystem.Models.Patient", "Patient")
                        .WithMany("Bills")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BillingSystem.Models.BillItem", b =>
                {
                    b.HasOne("BillingSystem.Models.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BillingSystem.Models.Insurance", b =>
                {
                    b.HasOne("BillingSystem.Models.Patient", "Patient")
                        .WithMany("Insurances")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BillingSystem.Models.LabOrder", b =>
                {
                    b.HasOne("BillingSystem.Models.Appointment", "Appointment")
                        .WithMany("LabOrders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BillingSystem.Models.PatientService", b =>
                {
                    b.HasOne("BillingSystem.Models.Patient", "Patient")
                        .WithMany("PatientServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BillingSystem.Models.ServiceMaster", "ServiceMaster")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("BillingSystem.Models.Payment", b =>
                {
                    b.HasOne("BillingSystem.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BillingSystem.Models.Prescription", b =>
                {
                    b.HasOne("BillingSystem.Models.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingSystem.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("BillingSystem.Models.Appointment", b =>
                {
                    b.Navigation("LabOrders");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("BillingSystem.Models.Bill", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BillingSystem.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BillingSystem.Models.Patient", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Appointments");

                    b.Navigation("Bills");

                    b.Navigation("Insurances");

                    b.Navigation("PatientServices");
                });
#pragma warning restore 612, 618
        }
    }
}
